# Generated by Django 6.0.7 on 2026-07-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_shared_by_post_shared_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shared_body',
            field=models.TextField(blank=True),
        ),
    ]
