# Generated by Django 6.0.7 on 2026-07-15 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_connections_connectionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionrequest',
            name='reciver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recived_connection_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_connection_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='connectionrequest',
            unique_together={('sender', 'reciver')},
        ),
    ]
