# Generated by Django 6.0.7 on 2026-07-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_connectionrequest_reciver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
