# Generated by Django 6.0.7 on 2026-07-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='views',
        ),
        migrations.AddField(
            model_name='profile',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
